name: renovate
on:
  schedule:
    - cron: '30 10 * * 5'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@957af03d760b2c87fc65cb95628f6d5f95d9c578 # v46.0.0
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: 'debug'
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
